import { NextRequest, NextResponse } from "next/server";
import {
  computeFourPillars,
  buildBaziProfile,
  type BaziProfile,
  type FourPillarsResult,
  type Gender,
} from "@/lib/bazi";
import {
  BAZI_ADVANCED_KNOWLEDGE_EN,
  BAZI_ADVANCED_KNOWLEDGE_ZH,
} from "@/lib/bazi-knowledge";
import { prisma } from "@/lib/prisma";
import { getSessionPayload } from "@/lib/auth";
import { getLocaleFromRequest, translate, type Locale } from "@/lib/i18n";
import { normalizeMembershipTier } from "@/lib/membership";

const GOOGLE_API_KEY = process.env.GEMINI_API_KEY_YISHUN
  ?? process.env.GOOGLE_API_KEY
  ?? process.env.GEMINI_API_KEY
  ?? process.env.GOOGLE_GENERATIVE_AI_API_KEY;
const GOOGLE_MODELS = [
  process.env.GOOGLE_MODEL,
  "gemini-2.5-flash",
  "gemini-2.0-flash",
  "gemini-1.5-flash-002",
  "gemini-1.5-flash",
  "gemini-1.5-pro",
].filter((model): model is string => Boolean(model));

const LAYER_A_PROMPT_EN = `You are an interpreter of a structured Ba Zi system. Output must be system-based and non-fatalistic.

Generate a concise daily signal based on the provided Ba Zi profile. Do NOT use any technical terms (no Day Master, no Four Pillars, no Heavenly Stems/Earthly Branches). Do NOT predict outcomes.

Requirements:
1. Tone: analytical, conditional, grounded
2. Output JSON only:

{
  "todaySignal": "1 concise sentence",
  "do": "1 actionable item",
  "avoid": "1 actionable item"
}

No extra text.`;

const LAYER_A_PROMPT_ZH = `你是结构化八字系统的解释者，输出必须是可追溯、非宿命的信号。

基于提供的八字画像生成今日信号。不得使用任何技术术语（不要出现日主/四柱/天干地支等），不要做预测。

要求：
1. 语气：理性、条件式、克制
2. 仅输出 JSON：

{
  "todaySignal": "1 句精炼信号",
  "do": "1 条可执行建议",
  "avoid": "1 条需避免事项"
}

不要输出额外文字。`;

const LAYER_B_PROMPT_EN = `You are an interpreter of a structured Ba Zi system. Output must be system-based and non-fatalistic.

Use standard terminology with brief explanations on first appearance: Ba Zi (Eight Characters / Four Pillars of Destiny), Day Master (Day Heavenly Stem), Heavenly Stems, Earthly Branches, Five Elements (Wood, Fire, Earth, Metal, Water).

Reference knowledge (Ba Zi fundamentals):
Five Elements (Wu Xing) are core for understanding a chart. Their generation/overcoming relationships run through every stem-branch combination and influence personality, career, wealth, relationships, and health.

1) Basic concepts
- Wood: growth and development; spring; East; benevolence and vitality.
- Fire: passion and light; summer; South; quick, intense, energetic.
- Earth: bearing and transformation; seasonal transitions; center; steady and grounded.
- Metal: firmness and contraction; autumn; West; sharp and decisive.
- Water: flow and wisdom; winter; North; flexible and deep.

2) Generation and overcoming
- Generating (sheng): Wood generates Fire, Fire generates Earth, Earth generates Metal, Metal generates Water, Water generates Wood.
  Generating indicates support; when one element is strong, it can help balance others through generation.
- Overcoming (ke): Wood controls Earth, Earth controls Water, Water controls Fire, Fire controls Metal, Metal controls Wood.
  Overcoming indicates restraint; when an element is too strong, use the controlling relation to harmonize the chart.
Balance is crucial. Ba Zi evaluates the Five Elements represented by stems and branches to judge whether the chart is coordinated.

3) Heavenly Stems and Earthly Branches mapping
- Heavenly Stems:
  Wood: Jia (Yang Wood), Yi (Yin Wood)
  Fire: Bing (Yang Fire), Ding (Yin Fire)
  Earth: Wu (Yang Earth), Ji (Yin Earth)
  Metal: Geng (Yang Metal), Xin (Yin Metal)
  Water: Ren (Yang Water), Gui (Yin Water)
- Earthly Branches:
  Wood: Yin, Mao
  Fire: Si, Wu
  Earth: Chen, Xu, Chou, Wei
  Metal: Shen, You
  Water: Zi, Hai

4) Five Elements balance in Ba Zi
If one element is too strong or too weak, the chart is imbalanced and life issues may appear. For example, excessive Fire can manifest as impatience; excessive Water can lead to emotional instability or lack of drive.
- Useful element (Yong Shen): the element the chart needs to strengthen or supplement, beneficial for restoring balance.
- Unfavorable element (Ji Shen): an element that is overly strong and should be restrained.
Example: if Fire is overly strong and Wood (which generates Fire) is also strong, Earth (generated by Fire) may be needed to drain Fire’s excess and restore balance.

5) Influence on life domains
- Wood: learning, growth, benevolence, ideals, education.
- Fire: career, authority, passion, creativity, decisiveness.
- Earth: stability, health, trust, tolerance; Earth balances the elements and supports steadiness.
- Metal: wealth, decisiveness, loyalty; symbol of money and resources.
- Water: wisdom, flexibility, emotions, flow; communication and emotional depth.
Imbalance shows as over- or under-expression in life. For example, excessive Water may bring rich emotions but weak execution; excessive Fire may bring leadership but also impulsiveness.

6) Five Elements adjustment
- Career selection: choose work aligned with favorable elements (e.g., Wood-strong suits education/publishing; Metal-strong suits finance/law).
- Living environment: adjust colors and directions (e.g., Water-weak may favor north and blue/black; Fire-weak may favor south and red/purple).
- Daily habits: diet, clothing, and activities can strengthen or reduce an element (e.g., Fire-strong may reduce spicy foods and increase water exposure to moderate heat).

Summary: The relationship between Ba Zi and Five Elements is foundational. Through generation/overcoming and favorable/unfavorable balance, one can interpret traits and trends. Balancing the elements helps guide life toward stability.

Ten Gods (Shi Shen)
Ten Gods are derived from the relationship between the Day Master (Day Stem) and other Heavenly Stems, based on generating/overcoming and Yin-Yang polarity. They describe how different energies relate to the self, reflecting traits, career dynamics, wealth patterns, and relational tendencies. Categories: produces me, I produce, controls me, I control, and same as me; each splits into Yin/Yang.

Terminology glossary (CN ↔ EN):
- 正财 (Zheng Cai) = Direct Wealth
- 偏财 (Pian Cai) = Indirect Wealth
- 正官 (Zheng Guan) = Direct Officer
- 七杀/偏官 (Qi Sha / Pian Guan) = Seven Killings / Indirect Officer
- 正印 (Zheng Yin) = Direct Resource
- 偏印/枭神 (Pian Yin / Xiao Shen) = Indirect Resource / Owl Spirit
- 食神 (Shi Shen) = Eating God
- 伤官 (Shang Guan) = Hurting Officer
- 比肩 (Bi Jian) = Peer
- 劫财 (Jie Cai) = Rob Wealth

1) Produces me (Resource)
- Direct Resource (Zheng Yin): supportive and protective; mother/elders, education, study, resources.
- Indirect Resource (Pian Yin, also called Owl Spirit): unconventional learning, intuition, alternative resources; can incline toward independence if excessive.

2) I produce (Output)
- Eating God (Shi Shen): talent, creativity, enjoyment, health, children.
- Hurting Officer (Shang Guan): self-expression, innovation, rule-challenging energy.

3) Controls me (Power)
- Direct Officer (Zheng Guan): discipline, responsibility, authority, work, reputation (also husband indicator in female charts).
- Seven Killings / Indirect Officer (Qi Sha / Pian Guan): pressure, competition, external challenges, strong impact.

4) I control (Wealth)
- Direct Wealth (Zheng Cai): stable wealth, duty, spouse, steady material accumulation.
- Indirect Wealth (Pian Cai): opportunity wealth, investments, side income, irregular gains; may indicate external relationship opportunities.

5) Same as me (Peers)
- Peer (Bi Jian): peers, siblings, independence, competition.
- Rob Wealth (Jie Cai): rivalry, resource drain, competitive cooperation.

Influence and combinations
- Direct Officer + Direct Resource often signals stable work norms and academic or professional support.
- Indirect Wealth + Seven Killings often signals risk-taking and competitive pressure in business contexts.

Adjustment
Evaluate favorable/unfavorable Ten Gods in the chart. If a category is weak, strengthen it through aligned roles or choices; if excessive, moderate via balancing elements and behaviors.

${BAZI_ADVANCED_KNOWLEDGE_EN}

Return JSON:
{
  "todaySignal": "1 concise sentence",
  "baziSignals": {
    "dayMasterExplanation": "1 sentence explaining Day Master",
    "favorableElement": "Element name",
    "favorableTime": "Time window",
    "favorableColor": "Color"
  },
  "whyThisSignal": "2-3 concise sentences explaining the signal"
}

No extra text.`;

const LAYER_B_PROMPT_ZH = `你是结构化八字系统的解释者，输出必须是可追溯、非宿命的信号。

使用标准术语并首次出现时给出简短解释：八字（四柱）、日主（日干）、天干、地支、五行（木火土金水）。

参考知识（八字基础）：
五行（木、火、土、金、水）是理解命局的核心。五行的生克关系贯穿于八字的天干地支组合，影响命主的性格、事业、财运、感情与健康。

一、五行的基本概念
- 木：代表生长与发展，象征春天、东方，木性仁慈、生机勃勃。
- 火：代表热情与光明，象征夏天、南方，火性急躁、热烈、充满能量。
- 土：代表承载与转化，象征季节过渡、中央，土性厚重、稳健。
- 金：代表坚固与收敛，象征秋天、西方，金性锐利、果断。
- 水：代表流动与智慧，象征冬天、北方，水性灵活、智慧深邃。

二、五行的生克关系
- 相生：木生火，火生土，土生金，金生水，水生木。
  相生表示促进与支持，某一五行旺盛时可通过相生让其他五行平衡。
- 相克：木克土，土克水，水克火，火克金，金克木。
  相克表示抑制与削弱，一种五行过旺时可通过克制关系调和命局能量。
五行平衡至关重要，八字通过分析天干地支所代表的五行来判断命局是否协调。

三、天干地支与五行的对应
- 天干：
  木：甲（阳木）、乙（阴木）
  火：丙（阳火）、丁（阴火）
  土：戊（阳土）、己（阴土）
  金：庚（阳金）、辛（阴金）
  水：壬（阳水）、癸（阴水）
- 地支：
  木：寅、卯
  火：巳、午
  土：辰、戌、丑、未
  金：申、酉
  水：子、亥

四、八字中的五行平衡
五行过强或过弱都会导致命局失衡。例如，火太旺可能性情急躁；水太旺容易情绪不稳、缺乏动力。
- 用神：命局中需要补充或增强的五行，对命主有利，能化解失衡。
- 忌神：命局中过于旺盛、需克制的五行，对命主不利，容易引发困扰。
例如，火过旺且木也强时，可用土（火生土）来泄火之力，使其趋于平衡。

五、五行对命运的影响
- 木：与学习、成长、仁爱、理想、教育相关。
- 火：与事业、权力、热情、创造力、决策力相关。
- 土：与稳定、健康、信任、包容相关，土能平衡五行，关系着安稳。
- 金：与财富、果断、义气相关，是金钱与资源的象征。
- 水：与智慧、灵活、感情、流动相关，代表沟通与情感深度。
失衡会表现为某方面不足或过度。例如，水过旺情感丰富但行动力不足；火过强有领导力但易冲动。

六、八字五行调理
- 职业选择：依据喜忌选择合适职业（如木旺适合教育/出版；金旺适合金融/法律）。
- 居住环境：调整颜色与方位（如水弱可取北方与蓝黑色；火弱可取南方与红紫色）。
- 日常习惯：通过饮食、穿衣、活动增强或削弱某一五行（如火旺减少辛辣，多接触水源）。

总结：五行与八字是命理学核心，通过生克制化、喜忌平衡可解析性格与趋势；平衡有助于生活稳定。

十神（Shi Shen）
十神以日干为中心，根据天干之间的生克与阴阳属性划分为十种关系，用于描述命主与外界的互动，反映性格、事业、财富、感情等。可归为生我、我生、克我、我克、我同五类，并各分阴阳。

术语对照（中英）：
- 正财（Zheng Cai / Direct Wealth）
- 偏财（Pian Cai / Indirect Wealth）
- 正官（Zheng Guan / Direct Officer）
- 七杀/偏官（Qi Sha / Pian Guan / Seven Killings / Indirect Officer）
- 正印（Zheng Yin / Direct Resource）
- 偏印/枭神（Pian Yin / Xiao Shen / Indirect Resource / Owl Spirit）
- 食神（Shi Shen / Eating God）
- 伤官（Shang Guan / Hurting Officer）
- 比肩（Bi Jian / Peer）
- 劫财（Jie Cai / Rob Wealth）

一、生我（印星）
- 正印：生我并扶助，代表母亲、长辈、学业、资源与保护。
- 偏印（枭神）：生我但偏门，代表非传统学识、灵感、另类资源；过旺易内敛孤僻。

二、我生（食伤）
- 食神：我生且有利，代表才华、健康、享乐、子女。
- 伤官：我生但不受控，代表表达、创造、反叛与突破。

三、克我（官杀）
- 正官：克我而规范，代表权力、责任、规则、工作、名誉；女性亦指丈夫。
- 七杀（偏官）：克我且冲击，代表竞争、压力、外部挑战。

四、我克（财星）
- 正财：我克而可得，代表稳定财富、责任、配偶与物质积累。
- 偏财：我克但不稳，代表机会财、投资、偏门财、外缘关系。

五、我同（比劫）
- 比肩：同类同气，代表朋友、同辈、独立与竞争。
- 劫财：同类异气，代表争夺、破财、合作消耗。

十神影响与组合
- 正官与正印：多见稳定的事业规范与学业支持。
- 偏财与七杀：多见商业竞争与压力并存的格局。

调理与应用
结合十神喜忌判断强弱：弱则补强，旺则节制，可通过职业选择、角色定位与行为模式进行平衡。

${BAZI_ADVANCED_KNOWLEDGE_ZH}

返回 JSON：
{
  "todaySignal": "1 句精炼信号",
  "baziSignals": {
    "dayMasterExplanation": "1 句解释日主",
    "favorableElement": "五行名称",
    "favorableTime": "有利时段",
    "favorableColor": "颜色"
  },
  "whyThisSignal": "2-3 句解释原因"
}

不要输出额外文字。`;

function isGender(value: string): value is Gender {
  return value === "male" || value === "female" || value === "other";
}

function formatFourPillars(bazi: FourPillarsResult, locale: Locale): string {
  const { year, month, day, hour } = bazi.fourPillars;
  if (locale === "zh-CN") {
    return [
      `年柱：${year.pillar}`,
      `月柱：${month.pillar}`,
      `日柱：${day.pillar}`,
      `时柱：${hour.pillar}`,
    ].join("，");
  }
  return [
    `Year Pillar (Heavenly Stem + Earthly Branch): ${year.pillar}`,
    `Month Pillar (Heavenly Stem + Earthly Branch): ${month.pillar}`,
    `Day Pillar (Heavenly Stem + Earthly Branch): ${day.pillar}`,
    `Hour Pillar (Heavenly Stem + Earthly Branch): ${hour.pillar}`,
  ].join(", ");
}

function formatTrueSolarTime(bazi: FourPillarsResult, locale: Locale): string {
  if (!bazi.trueSolarTime) {
    return locale === "zh-CN" ? "未应用真太阳时" : "True Solar Time not applied";
  }
  const { date, time, offsetMinutes } = bazi.trueSolarTime;
  if (locale === "zh-CN") {
    return `真太阳时：${date} ${time}（偏移 ${offsetMinutes} 分钟）`;
  }
  return `True Solar Time: ${date} ${time} (offset ${offsetMinutes} min)`;
}

function formatGenderForPrompt(gender: Gender, locale: Locale): string {
  if (locale === "zh-CN") {
    if (gender === "male") return "男";
    if (gender === "female") return "女";
    return "其他";
  }
  if (gender === "male") return "Male";
  if (gender === "female") return "Female";
  return "Other";
}

function buildUserPrompt(
  locale: Locale,
  birthDate: string,
  birthTime: string,
  gender: Gender,
  bazi: FourPillarsResult
): string {
  if (locale === "zh-CN") {
    return `我的出生信息：
- 出生日期：${birthDate}
- 出生时间：${birthTime}
- 性别：${formatGenderForPrompt(gender, locale)}
- ${formatTrueSolarTime(bazi, locale)}
- 四柱（八字）：${formatFourPillars(bazi, locale)}

请生成今日运势。`;
  }

  return `My birth information:
- Birth Date: ${birthDate}
- Birth Time: ${birthTime}
- Gender: ${formatGenderForPrompt(gender, locale)}
- ${formatTrueSolarTime(bazi, locale)}
- Four Pillars (Ba Zi / Four Pillars of Destiny): ${formatFourPillars(bazi, locale)}

Please generate my daily fortune.`;
}

function buildLayerPrompt(locale: Locale, layer: "A" | "B"): string {
  if (layer === "A") {
    return locale === "zh-CN" ? LAYER_A_PROMPT_ZH : LAYER_A_PROMPT_EN;
  }
  return locale === "zh-CN" ? LAYER_B_PROMPT_ZH : LAYER_B_PROMPT_EN;
}

function isSameDay(left: Date, right: Date) {
  return (
    left.getFullYear() === right.getFullYear() &&
    left.getMonth() === right.getMonth() &&
    left.getDate() === right.getDate()
  );
}

type LocationInfo = {
  longitude: number | null;
  latitude: number | null;
  timezoneName: string | null;
  timezoneOffsetMinutes: number | null;
};

function parseUtcOffset(value: string): number | null {
  const match = value.match(/^([+-])(\d{2})(\d{2})$/);
  if (!match) {
    return null;
  }
  const sign = match[1] === "-" ? -1 : 1;
  const hours = Number(match[2]);
  const minutes = Number(match[3]);
  if (Number.isNaN(hours) || Number.isNaN(minutes)) {
    return null;
  }
  return sign * (hours * 60 + minutes);
}

async function resolveLocation(request: Request): Promise<LocationInfo> {
  const forwarded = request.headers.get("x-forwarded-for");
  const realIp = request.headers.get("x-real-ip");
  const ip = (forwarded?.split(",")[0] || realIp || "").trim();
  const url = ip ? `https://ipapi.co/${ip}/json/` : "https://ipapi.co/json/";

  try {
    const response = await fetch(url, { cache: "no-store" });
    if (!response.ok) {
      return {
        longitude: null,
        latitude: null,
        timezoneName: null,
        timezoneOffsetMinutes: null,
      };
    }
    const data = await response.json();
    const longitude = Number(data.longitude);
    const latitude = Number(data.latitude);
    const utcOffset = typeof data.utc_offset === "string" ? data.utc_offset : null;
    const timezoneOffsetMinutes = utcOffset ? parseUtcOffset(utcOffset) : null;
    return {
      longitude: Number.isFinite(longitude) ? longitude : null,
      latitude: Number.isFinite(latitude) ? latitude : null,
      timezoneName: typeof data.timezone === "string" ? data.timezone : null,
      timezoneOffsetMinutes,
    };
  } catch {
    return {
      longitude: null,
      latitude: null,
      timezoneName: null,
      timezoneOffsetMinutes: null,
    };
  }
}

async function generateFortuneWithGoogle(
  birthDate: string,
  birthTime: string,
  gender: Gender,
  bazi: FourPillarsResult,
  locale: Locale,
  layer: "A" | "B",
  baziProfile: BaziProfile
) {
  const userPrompt = buildUserPrompt(locale, birthDate, birthTime, gender, bazi);
  const systemPrompt = buildLayerPrompt(locale, layer);
  const profilePayload = JSON.stringify(baziProfile, null, 2);

  const models = Array.from(new Set(GOOGLE_MODELS));
  const modelErrors: string[] = [];

  for (const model of models) {
    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GOOGLE_API_KEY}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            contents: [{
              parts: [
                {
                  text:
                    systemPrompt +
                    "\n\nBa Zi Profile (precomputed):\n" +
                    profilePayload +
                    "\n\n" +
                    userPrompt,
                },
              ],
            }],
            generationConfig: {
              temperature: 0.8,
              responseMimeType: "application/json"
            }
          })
        }
      );

      if (!response.ok) {
        const error = await response.text();
        throw new Error(`Google API Error: ${response.status} - ${error}`);
      }

      const data = await response.json();
      const fortuneText = data.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!fortuneText) {
        throw new Error(translate(locale, "errors.fortuneFailed"));
      }

      try {
        return JSON.parse(fortuneText);
      } catch {
        const jsonMatch = fortuneText.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          return JSON.parse(jsonMatch[0]);
        }
        throw new Error(translate(locale, "errors.fortuneFailed"));
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      modelErrors.push(`${model}: ${message}`);
    }
  }

  throw new Error(`All Google models failed. ${modelErrors.join(" | ")}`);
}

export async function POST(request: NextRequest) {
  try {
    const locale = getLocaleFromRequest(request);
    const t = (key: Parameters<typeof translate>[1]) => translate(locale, key);

    const session = await getSessionPayload(request);
    if (!session) {
      return NextResponse.json(
        { error: t("errors.authRequired") },
        { status: 401 }
      );
    }

    const {
      birthDate,
      birthTime,
      gender,
      longitude,
      latitude,
      timezoneOffsetMinutes,
      timezoneName,
    } = await request.json();

    const user = await prisma.user.findUnique({ where: { id: session.sub } });
    if (!user) {
      return NextResponse.json(
        { error: t("errors.unauthorized") },
        { status: 401 }
      );
    }

    const resolvedBirthDate =
      typeof birthDate === "string" ? birthDate : user?.birthDate ?? null;
    const resolvedBirthTime =
      typeof birthTime === "string" ? birthTime : user?.birthTime ?? null;
    const resolvedGenderRaw =
      typeof gender === "string" ? gender : user?.gender ?? null;

    if (!resolvedBirthDate || !resolvedBirthTime || !resolvedGenderRaw) {
      return NextResponse.json(
        { error: t("errors.profileIncomplete") },
        { status: 400 }
      );
    }

    const normalizedGender = resolvedGenderRaw.toLowerCase();
    if (!isGender(normalizedGender)) {
      return NextResponse.json(
        { error: t("errors.invalidGender") },
        { status: 400 }
      );
    }

    if (!GOOGLE_API_KEY) {
      return NextResponse.json(
        { error: t("errors.googleKeyMissing") },
        { status: 500 }
      );
    }

    const tier = normalizeMembershipTier(user.planTier);
    const requestedLayer = tier === "free" ? "A" : "B";

    if (requestedLayer === "A") {
      const lastWatch = user.lastAdWatchedAt;
      if (!lastWatch || !isSameDay(lastWatch, new Date())) {
        return NextResponse.json(
          { error: t("errors.adRequired") },
          { status: 403 }
        );
      }
    }

    const parsedLongitude =
      typeof longitude === "number" && Number.isFinite(longitude)
        ? longitude
        : null;
    const parsedLatitude =
      typeof latitude === "number" && Number.isFinite(latitude)
        ? latitude
        : null;
    const parsedTimezoneOffset =
      typeof timezoneOffsetMinutes === "number" &&
      Number.isFinite(timezoneOffsetMinutes)
        ? timezoneOffsetMinutes
        : null;
    const parsedTimezoneName =
      typeof timezoneName === "string" ? timezoneName : null;

    const resolvedLocation = await resolveLocation(request);
    const resolvedLongitude = parsedLongitude ?? resolvedLocation.longitude;
    const resolvedLatitude = parsedLatitude ?? resolvedLocation.latitude;
    const resolvedTimezoneOffset =
      parsedTimezoneOffset ?? resolvedLocation.timezoneOffsetMinutes;
    const resolvedTimezoneName = parsedTimezoneName ?? resolvedLocation.timezoneName;

    if (user && !user.birthDate && resolvedBirthDate && resolvedBirthTime) {
      await prisma.user.update({
        where: { id: user.id },
        data: {
          birthDate: resolvedBirthDate,
          birthTime: resolvedBirthTime,
          gender: normalizedGender,
          longitude: resolvedLongitude,
          latitude: resolvedLatitude,
          timezoneOffsetMinutes: resolvedTimezoneOffset ?? null,
          timezoneName: resolvedTimezoneName,
        },
      });
    }

    const bazi = computeFourPillars({
      birthDate: resolvedBirthDate,
      birthTime: resolvedBirthTime,
      gender: normalizedGender,
      longitude: resolvedLongitude,
      latitude: resolvedLatitude,
      timezoneOffsetMinutes: resolvedTimezoneOffset ?? undefined,
      timezoneName: resolvedTimezoneName ?? undefined,
    });
    const baziProfile = buildBaziProfile(bazi);

    const result = await generateFortuneWithGoogle(
      resolvedBirthDate,
      resolvedBirthTime,
      normalizedGender,
      bazi,
      locale,
      requestedLayer,
      baziProfile
    );

    if (requestedLayer === "A") {
      if (!result?.todaySignal || !result?.do || !result?.avoid) {
        throw new Error(t("errors.fortuneFailed"));
      }
      return NextResponse.json({
        layer: "A",
        signal: {
          todaySignal: result.todaySignal,
          do: result.do,
          avoid: result.avoid,
          attribution: t("layerA.attribution"),
        },
      });
    }

    if (!result?.todaySignal || !result?.baziSignals || !result?.whyThisSignal) {
      throw new Error(t("errors.fortuneFailed"));
    }

    return NextResponse.json({
      layer: "B",
      signal: {
        todaySignal: result.todaySignal,
        baziSignals: {
          dayMaster: baziProfile.day_master,
          dayMasterExplanation: result.baziSignals?.dayMasterExplanation,
          favorableElement: result.baziSignals?.favorableElement,
          favorableTime: result.baziSignals?.favorableTime,
          favorableColor: result.baziSignals?.favorableColor,
        },
        whyThisSignal: result.whyThisSignal,
      },
    });
  } catch (error) {
    console.error("Fortune API Error:", error);

    const message = error instanceof Error ? error.message : "Unknown error";
    const locale = getLocaleFromRequest(request);
    const payload = { error: translate(locale, "errors.fortuneRetry") };

    if (process.env.NODE_ENV !== "production") {
      return NextResponse.json({ ...payload, details: message }, { status: 500 });
    }

    return NextResponse.json(payload, { status: 500 });
  }
}
